### ISSUE TITLE
Litmus is in the wrong ruby group

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-module-gems#103]
The Litmus gem requires Puppet 6 which requires Ruby 2.5.  However in https://github.com/puppetlabs/puppet-module-gems/blob/15d1f27c0c602026a731e57642c9ba21c396e3aa/config/dependencies.yml#L30-L31 litmus is in the default.

The litmus gem should only be in the Ruby 2.5, 2.6 system gems otherwise it blocks any use of 0.4.x on Ruby 2.4 and less

ping @rodjek

**Comment by tphoney** [comment]
were you thinking something like #104

**Comment by rodjek** [comment]
Fixed by #104
