### ISSUE TITLE
Please publish gems for Ruby 2.7

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-module-gems#127]
## Use Case

Hi people, since this project started some time ago, I'm unable to execute the puppetlabs test suite locally every spring :( Ruby 2.7 is stable since months, but you don't publish gems for that. Cold you please update it?

## Describe the Solution You Would Like

I want that a simple `bundle install` within any of the official Puppet Inc. modules work and pulls in Ruby 2.7 specifc gems.

## Describe Alternatives You've Considered

Patching the Gemfile to pull in the older 2.6 gems works, but that's annoying and currently one of the blockers for rolling out pdk to Vox Pupuli modules.

## Additional Context

There is a regular release schedule for Ruby with a big release every year around christmas. I would like to see a process to build new gems for those versions early / automated.

**Comment by freibuis** [comment]
I would agree, but remember the puppet version that you are using should determine what version of ruby your module is uses.
```bash
/opt/puppetlabs/puppet/bin/ruby -v
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
```

I say this because if you deploy code based on a new version a few things might break.  if you do want to use a new version then just make sure you are not using any syntax that is not supported by the ruby version of what puppet is using.

**Comment by bastelfreak** [comment]
Hello @freibuis. I am aware of  this. There are many operating systems out there where Puppet does not provide an AIO package with a vendored old ruby. Also we noticed at Vox Pupuli that the used ruby version for tests, as long as it's MRI, does not really make a difference for the testsuite to succeed. Most people just don't want to use a ruby wrapper like rvm, but their system ruby.
