### ISSUE TITLE
Codecov yanked older versions, including the one used as a dependency

### ISSUE THREAD

**Issue by LMacchi** [puppetlabs/puppet-module-gems#138]
## Describe the Bug
Dependency for this gem include 
```
gem: codecov
          version: '~> 0.1.10'
```

However all 1.x codecov versions were removed from Rubygems, as explained in this deprecation notice: https://github.com/codecov/codecov-ruby/issues/87. 

As a consequence, trying to download `puppet-module-posix-dev-*` results in:

```
Bundler could not find compatible versions for gem "codecov":
  In Gemfile:
puppet-module-posix-dev-r2.4 (~> 0.4) was resolved to 0.5.0, which depends
on
      codecov (~> 0.1.10)
Could not find gem 'codecov (~> 0.1.10)', which is required by gem
'puppet-module-posix-dev-r2.4 (~> 0.4)', in any of the sources.
```

## Expected Behavior
I expected the gem to be installed successfully

## Steps to Reproduce
- Create a Gemfile including `puppet-module-posix-dev-*`
- Run `bundle install`

**Comment by pmcmaw** [comment]
Thank you for raising this issue @LMacchi, 
We are currently working on resolving this issue. 👍

**Comment by kelbyers** [comment]
We are stuck using puppet-module-posix-dev-r2.4, which requires `codecov ~> 0.1.10`. I am perfectly fine with you not wanting to support older versions, but removing the gems from RubyGems is breaking our environment.
