### ISSUE TITLE
Missing ruby 2.1 pins

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/puppet-module-gems#142]
I've found I've also had to pin `public_suffix` to `3.1.1` and `parallel` to `1.13.0`.
Should I add them [here](https://github.com/puppetlabs/puppet-module-gems/blob/8855bec7882d5af7f6289a112a9789c1661367fb/config/dependencies.yml#L89), or am I missing something?

**Comment by DavidS** [comment]
That sounds sensible, we're not using ruby2.1 actively anymore, but will happily release any community finds.

**Comment by DavidS** [comment]
We're dropping ruby 2.1 support with the upcoming 1.0.0 release, so I'm gonna close this.
