### ISSUE TITLE
Dependency on specinfra

### ISSUE THREAD

**Issue by mijamill** [puppetlabs/puppet-module-gems#80]
Current dependency on specinfra is causing failures in windows spec testing. V2.67.3 requires net-ssh < 5.0, but >=5.0 is needed to start windows spec testing as it maintains a patch to the error referenced below. Below is a screen shot of the current error being caused. I have manually changed specinfra's dependencies in the gemfile.lock in my local testing and it then runs correctly, but as soon as I run bundle update it reverts back to a prior version of net-ssh due to this dependency.
<img width="461" alt="screen shot 2018-08-24 at 9 20 27 am" src="https://user-images.githubusercontent.com/11684044/44586946-657a5000-a77f-11e8-9525-c88a3afc4b4f.png">

**Comment by david22swan** [comment]
Specinfra version has been bumped to 2.76.7
