### ISSUE TITLE
Could not find gem 'puppet-module-posix-default-r2.6'

### ISSUE THREAD

**Issue by Felixoid** [puppetlabs/puppet-module-gems#93]
Hello. Since ruby 2.6 was released, could you please deploy the module for it to rubygems.org?

**Comment by tphoney** [comment]
The reason this has not been done yet, is because the latest puppet agent is still 2.5. 2.6 will likely happen when the agent updates.

**Comment by Felixoid** [comment]
Hey @tphoney, thank you for info. Any ETA about it?
